name: Docker Compose

on:
  push:
    branches:
      - be-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name : JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: create properties
        run: touch ./be/src/main/resources/application-prod.properties
      - run: echo "${{ secrets.PROPERTIES }}" > ./be/src/main/resources/application-prod.properties
        shell: bash
        
      - name: grant gradlew
        run: |
          cd ./be
          chmod +x ./gradlew

      - name: Build with gradle
        run: |
          cd ./be
          ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image Processing
        run: |
          cd ./be
          docker build -t seondays/issue-tracker:latest .
          docker push seondays/issue-tracker:latest

      - name: SSH Processing
        uses: appleboy/ssh-action@v0.1.6
        with: 
          key: ${{secrets.GROMIT_KEY}}
          host: ${{secrets.GROMIT_EC2_HOST}}
          username: ${{secrets.GROMIT_USER_NAME}}
          port: ${{secrets.SSH_PORT}}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Pull new image and Run
        run: |
          sudo docker pull seondays/issue-tracker:latest
          sudo docker-compose down
          sudo docker-compose -f docker-compose.yml up -d
    

    
